name: Publish

on:
  release:
    types: [published]

  workflow-dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # fetch all branches, not just triggering branch

    - run: python3 -m pip install --upgrade build && python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with: 
        password: pypa/gh-action-pypi-publish@release/v1